defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: projects
    values:
      layout: "project"
collections:
  projects:
    output: true
